version: '2'
services:
    fixedassetstransfer-app:
        image: fixedassetstransfer
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fixedassetstransfer-mysql:3306/fixedassetstransfer?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=fixedassetstransfer-elasticsearch:9300
        ports:
            - 8080:8080
    fixedassetstransfer-mysql:
        extends:
            file: mysql.yml
            service: fixedassetstransfer-mysql
    fixedassetstransfer-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: fixedassetstransfer-elasticsearch
